fixtures:
  repositories:
    registry:
      repo: 'git://github.com/puppetlabs/puppetlabs-registry.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    reboot:
      repo: 'git://github.com/puppetlabs/puppetlabs-reboot.git'
  symlinks:
    windows_disable_ipv6: "#{source_dir}"
