fixtures:
  repositories:
    registry: 'https://github.com/puppetlabs/puppetlabs-registry.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    reboot: 'https://github.com/puppetlabs/puppetlabs-reboot.git'
  symlinks:
    windows_disable_ipv6: "#{source_dir}"
